name: Staging
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Staging Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ~/api
            git pull
            go get
            go build
            pm2 reload DEL-API-STAGING
          host: ${{ secrets.HOST }}
          username: cairo
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        env:
          CI: true