name: Production
on:
  release:
    types:
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ~/api-stable
            git pull
            go get
            go build
            pm2 reload DEL-API
          host: ${{ secrets.HOST }}
          username: cairo
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        env:
          CI: true